Repository PerigonGames/BForBoss, pull requests merged in 2021-10, with the labels that each got.

#1 Added WorldManager and StateManager
  Assets/ECM2/Samples/Examples/6.- Cinemachine/Cinemachine Examples.unitypackage.meta
  Assets/ECM2/Samples/Examples/7.- Bolt/Bolt Examples.unitypackage.meta
  Assets/Plugins/Sirenix/Demos/Editor Windows.unitypackage.meta
  Assets/_BForBoss/Scripts/Editor.meta
  Assets/_BForBoss/_LevelDesign/ManagerScene.unity
  Assets/_BForBoss/_LevelDesign/ManagerScene.unity.meta
  Assets/_BForBoss/_LevelDesign/Managers.meta
  Assets/_BForBoss/_LevelDesign/Managers/StateManager.cs
  Assets/_BForBoss/_LevelDesign/Managers/StateManager.cs.meta
  Assets/_BForBoss/_LevelDesign/Managers/WorldManager.cs
  Assets/_BForBoss/_LevelDesign/Managers/WorldManager.cs.meta
  UserSettings/EditorUserSettings.asset
Labels: enhancement

#12 BFB-21
  Assets/_BForBoss/_LevelDesign/ManagerScene.unity
  Assets/_BForBoss/_LevelDesign/Managers/StateManager.cs
  Assets/_BForBoss/_LevelDesign/Managers/TimeManager.cs
  Assets/_BForBoss/_LevelDesign/Managers/TimeManager.cs.meta
  Assets/_BForBoss/_LevelDesign/Managers/WorldManager.cs
Labels: enhancement, autosquash

#18 Martin/Add Dotween
  Assets/Plugins/Demigiant.meta
  Assets/Plugins/Demigiant/DOTween.meta
  Assets/Plugins/Demigiant/DOTween/DOTween.XML
  Assets/Plugins/Demigiant/DOTween/DOTween.XML.meta
  Assets/Plugins/Demigiant/DOTween/DOTween.dll
  Assets/Plugins/Demigiant/DOTween/DOTween.dll.meta
  Assets/Plugins/Demigiant/DOTween/Editor.meta
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.XML
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.XML.meta
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.dll
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.dll.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenIcon.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenIcon.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenMiniIcon.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenMiniIcon.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer_dark.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer_dark.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Header.jpg
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Header.jpg.meta
  Assets/Plugins/Demigiant/DOTween/Modules.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleAudio.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleAudio.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleEPOOutline.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleEPOOutline.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics2D.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics2D.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleSprite.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleSprite.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUI.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUI.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUnityVersion.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUnityVersion.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUtils.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUtils.cs.meta
  Assets/Plugins/Demigiant/DOTween/readme.txt
  Assets/Plugins/Demigiant/DOTween/readme.txt.meta
  Assets/Resources.meta
  Assets/Resources/DOTweenSettings.asset
  Assets/Resources/DOTweenSettings.asset.meta
Labels: autosquash

#16 BFB-29: Unit tests Setup
  Assets/ECM2/ECM2.asmdef
  Assets/ECM2/ECM2.asmdef.meta
  Assets/Shapes/Samples/Assets/Capsules.mat
  Assets/Shapes/Samples/Assets/Ground.mat
  Assets/_BForBoss/Tests.meta
  Assets/_BForBoss/Tests/CharacterMovementTests.cs
  Assets/_BForBoss/Tests/CharacterMovementTests.cs.meta
  Assets/_BForBoss/Tests/InputActions.meta
  Assets/_BForBoss/Tests/InputActions/Test_BFB_FPS_InputActions.inputactions
  Assets/_BForBoss/Tests/InputActions/Test_BFB_FPS_InputActions.inputactions.meta
  Assets/_BForBoss/Tests/Scenes.meta
  Assets/_BForBoss/Tests/Scenes/CharacterMovementTest.unity
  Assets/_BForBoss/Tests/Scenes/CharacterMovementTest.unity.meta
  Assets/_BForBoss/Tests/Tests.asmdef
  Assets/_BForBoss/Tests/Tests.asmdef.meta
  Assets/_BForBoss/_Character/Character.asmdef
  Assets/_BForBoss/_Character/Character.asmdef.meta
  Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.cs
  Packages/manifest.json
Labels: autosquash

#20 BFB-22: Working Checkpoint Management
  Assets/_BForBoss/Prefabs/Checkpoint.prefab
  Assets/_BForBoss/Prefabs/Checkpoint.prefab.meta
  Assets/_BForBoss/_LevelDesign/Managers/CheckpointManager.cs
  Assets/_BForBoss/_LevelDesign/Managers/CheckpointManager.cs.meta
  Assets/_BForBoss/_LevelDesign/Managers/TimeManager.cs
  Assets/_BForBoss/_LevelDesign/Managers/WorldManager.cs
  Assets/_BForBoss/_LevelDesign/Scenes/CheckpointCourse.unity
  Assets/_BForBoss/_LevelDesign/Scenes/CheckpointCourse.unity.meta
  Assets/_BForBoss/_LevelDesign/Scenes/ManagerScene.unity
  Assets/_BForBoss/_LevelDesign/Scenes/ManagerScene.unity.meta
  Assets/_BForBoss/_LevelDesign/Scripts/Checkpoint.cs
  Assets/_BForBoss/_LevelDesign/Scripts/Checkpoint.cs.meta
  Assets/_BForBoss/_LevelDesign/Scripts/Tags.cs
  Assets/_BForBoss/_LevelDesign/Scripts/Tags.cs.meta
Labels: enhancement

#19 BFB-35: Base Wall Running Mechanic
  Assets/_BForBoss/_Character/Prefabs/PlayerRoot.prefab
  Assets/_BForBoss/_Character/Prefabs/Sandbox.prefab
  Assets/_BForBoss/_Character/Scenes/Sandbox.unity
  Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.cs
  Assets/_BForBoss/_Character/Scripts/PlayerWallRunBehaviour.cs
  Assets/_BForBoss/_Character/Scripts/PlayerWallRunBehaviour.cs.meta
  ProjectSettings/TagManager.asset
Labels: autosquash

#22 Martin: Character Dash Tests
  Assets/_BForBoss/Tests/CharacterDashTests.cs
  Assets/_BForBoss/Tests/CharacterDashTests.cs.meta
  Assets/_BForBoss/Tests/Scenes/CharacterDashTest.unity
  Assets/_BForBoss/Tests/Scenes/CharacterDashTest.unity.meta
  Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.cs
  Assets/_BForBoss/_Character/Scripts/PlayerDashBehaviour.cs
Labels: autosquash

#26 Michael/ecm2 build errors
  Assets/ECM2/Source/Editor/ECM2FactoryEditor.cs
Labels: bug fix, autosquash

#45 BFB-62: Analytics for checkpoints
  Assets/_BForBoss/Scripts/Managers/CheckpointManager.cs
  Assets/_BForBoss/Scripts/Managers/WorldManager.cs
  Assets/_BForBoss/_Analytics/Scripts/PerigonAnalytics.cs
Labels: autosquash

#47 BFB-64: Set username property
  Assets/_BForBoss/Scripts/Managers/WorldManager.cs
  Assets/_BForBoss/_Analytics/Scripts/PerigonAnalytics.cs
  Assets/_BForBoss/_Leaderboard/Scripts/InputUsernameViewBehaviour.cs
  Assets/_BForBoss/_Leaderboard/Scripts/Leaderboard.asmdef
Labels: autosquash
