Repository PerigonGames/BForBoss, pull requests merged in 2022-03, with the labels that each got.

#126 BFB-205 : Decouple SceneSwitcher from BForBoss with Settings Provider
  Assets/_BForBoss/_Utility/Scripts/Editor/SceneSwitcher/SceneConfigSetup.cs
  Assets/_BForBoss/_Utility/Scripts/Editor/SceneSwitcher/SceneSwitcherEditorWindow.cs
  Assets/_BForBoss/_Utility/Scripts/Editor/SceneSwitcher/SceneSwitcherSettingsProvider.cs
  Assets/_BForBoss/_Utility/Scripts/Editor/SceneSwitcher/SceneSwitcherSettingsProvider.cs.meta
Labels: Refactor

#134 BFB-223 : Added Entity Kill Counter for WeaponRaceCourse World
  Assets/_BForBoss/_Core/Prefabs/UserInterface/EntityCounterCanvas.prefab
  Assets/_BForBoss/_Core/Prefabs/UserInterface/EntityCounterCanvas.prefab.meta
  Assets/_BForBoss/_Core/Scripts/Managers/WeaponRaceCourseWorldManager.cs
  Assets/_BForBoss/_Core/Scripts/TimerViewBehaviour.cs
  Assets/_BForBoss/_Core/Scripts/UserInterface/EntityCounterViewBehaviour.cs
  Assets/_BForBoss/_Core/Scripts/UserInterface/EntityCounterViewBehaviour.cs.meta
  Assets/_BForBoss/_Entities/Scripts/LifeCycle.cs
  Assets/_BForBoss/_Entities/Scripts/LifeCycleBehaviour.cs
  Assets/_BForBoss/_Entities/Scripts/LifeCycleManager.cs
  Assets/_BForBoss/_LevelDesign/Scenes/MS2_RaceCourse.unity
Labels: enhancement

#130 BFB-212
  FMODAssets/Build/Desktop/Master.bank
  FMODAssets/Build/Desktop/Master.strings.bank
  FMODAssets/Metadata/Event/{150ae508-3299-4a3b-91d3-11d1f6a946ee}.xml
  FMODAssets/Metadata/Event/{343391a5-26d7-4574-bb3c-cf496f0ac2c9}.xml
  FMODAssets/Metadata/Event/{36fbc6a5-c9a0-44fd-8c44-0013a8125d69}.xml
  FMODAssets/Metadata/Event/{4aa13862-c6cb-43b6-95be-8e3ac198c03b}.xml
  FMODAssets/Metadata/Event/{66356b52-6186-4ef2-8a8d-38474212c3fb}.xml
  FMODAssets/Metadata/Event/{6cdc22c2-5cc8-4a16-9667-856632ddc678}.xml
  FMODAssets/Metadata/Event/{9c595d95-9c82-448a-b1bc-289c019051ed}.xml
  FMODAssets/Metadata/Event/{a8a52b8e-f392-40dc-a182-137ca06f633a}.xml
  FMODAssets/Metadata/Event/{aa22e30e-f1c1-4ddc-bb6a-9165804ca5e3}.xml
  FMODAssets/Metadata/Event/{b46f6210-aadc-49b6-a224-5b8c7e650037}.xml
  FMODAssets/Metadata/Event/{c0a42275-49b2-472d-a71e-400946aa708d}.xml
  FMODAssets/Metadata/Event/{edf3d034-e8d3-4d9a-a486-a04ed0c11e8e}.xml
  FMODAssets/Metadata/Group/{06ff72a3-e5ff-4a5e-8668-a9cff1ca3d97}.xml
  FMODAssets/Metadata/Group/{10d8d637-6da4-4516-aed5-1f6a071e8c23}.xml
  FMODAssets/Metadata/Group/{83170379-bc58-4ebb-ad15-ae2a52980f43}.xml
  FMODAssets/Metadata/Group/{f39f09c9-3a2f-4bd3-a7fc-31f73764ea0f}.xml
Labels: enhancement

#145 BFB-192: Fix character movement audio bug
  Assets/_BForBoss/_Character/Scripts/FirstPersonPlayer.cs
  Assets/_BForBoss/_Character/Scripts/PlayerDashBehaviour.cs
  Assets/_BForBoss/_Character/Scripts/PlayerSlideBehaviour.cs
Labels: bug fix

#146 BFB-244: Changed Enemy Sounds and Background music to be 2D
  FMODAssets/Build/Desktop/Master.bank
  FMODAssets/Build/Desktop/Master.strings.bank
  FMODAssets/Metadata/Event/{4aa13862-c6cb-43b6-95be-8e3ac198c03b}.xml
  FMODAssets/Metadata/Event/{66356b52-6186-4ef2-8a8d-38474212c3fb}.xml
  FMODAssets/Metadata/Event/{a8a52b8e-f392-40dc-a182-137ca06f633a}.xml
  FMODAssets/Metadata/Event/{b46f6210-aadc-49b6-a224-5b8c7e650037}.xml
  FMODAssets/Metadata/Event/{c0a42275-49b2-472d-a71e-400946aa708d}.xml
  FMODAssets/Metadata/Event/{edf3d034-e8d3-4d9a-a486-a04ed0c11e8e}.xml
Labels: bug fix
