Repository PerigonGames/BForBoss, pull requests merged in 2022-02, with the labels that each got.

#104 BFB-134 : Sandbox SceneTemplate
  Assets/_BForBoss/_Core/SceneTemplates.meta
  Assets/_BForBoss/_Core/SceneTemplates/SandboxSceneTemplate.meta
  Assets/_BForBoss/_Core/SceneTemplates/SandboxSceneTemplate/SandboxSceneTemplate.scenetemplate
  Assets/_BForBoss/_Core/SceneTemplates/SandboxSceneTemplate/SandboxSceneTemplate.scenetemplate.meta
  Assets/_BForBoss/_Core/SceneTemplates/SandboxSceneTemplate/SandboxSceneTemplate.unity
  Assets/_BForBoss/_Core/SceneTemplates/SandboxSceneTemplate/SandboxSceneTemplate.unity.meta
  ProjectSettings/SceneTemplateSettings.json
Labels: enhancement

#106 BFB-148: Change enemy health to be 10
  Assets/_BForBoss/_Entities/Scripts/ScriptableObjects/HealthProperties.asset
Labels: autosquash

#108 Gursaanj/BFB-195 : SceneSwticher EditorWindow
  Assets/_BForBoss/_Utility/Scripts/Editor/SceneSwitcher.meta
  Assets/_BForBoss/_Utility/Scripts/Editor/SceneSwitcher/SceneConfigSetup.cs
  Assets/_BForBoss/_Utility/Scripts/Editor/SceneSwitcher/SceneConfigSetup.cs.meta
  Assets/_BForBoss/_Utility/Scripts/Editor/SceneSwitcher/SceneSwitcherEditorWindow.cs
  Assets/_BForBoss/_Utility/Scripts/Editor/SceneSwitcher/SceneSwitcherEditorWindow.cs.meta
Labels: autosquash

#110 BFB-184: Fix for object pooler and scene switching
  Assets/_BForBoss/_Utility/Scripts/ObjectPooler.cs
Labels: autosquash

#111 BFB-179: Fixed up Dummies in scene
  Assets/_BForBoss/_Entities/Animation/DummyController.controller
  Assets/_BForBoss/_Entities/Prefabs/Dummy.prefab
Labels: autosquash

#114 Wbeltran/fmod events
  FMODAssets/Build/Desktop/Master.bank
  FMODAssets/Build/Desktop/Master.strings.bank
  FMODAssets/Metadata/Asset/{284c8086-a6a1-4628-9715-b980e9dc992b}.xml
  FMODAssets/Metadata/Asset/{4c8f69fe-6c5e-4008-a3fc-d2b344710c7d}.xml
  FMODAssets/Metadata/Asset/{aad722e2-830a-479d-b491-27a6f22c4cae}.xml
  FMODAssets/Metadata/Asset/{d961bc0f-31d8-4ede-9905-7bd367ce2adc}.xml
  FMODAssets/Metadata/Asset/{dd2e4e8c-2ace-473c-b56d-ec3c5442f96e}.xml
  FMODAssets/Metadata/Asset/{e1554164-c595-4429-8397-b074fcdf4b2f}.xml
  FMODAssets/Metadata/AudioFile/{01f57156-506f-40f3-a97f-5110c93a0964}.xml
  FMODAssets/Metadata/AudioFile/{6eac8dd5-3be5-4a02-a90f-e3a1cc639f2b}.xml
  FMODAssets/Metadata/AudioFile/{7405210e-9a53-4fe2-aaaa-08e104a22e9f}.xml
  FMODAssets/Metadata/AudioFile/{9da40ca9-fd33-45df-9b7a-ca8906b55e3b}.xml
  FMODAssets/Metadata/AudioFile/{a73c722f-5e1e-4ba4-9eea-82de1d1d37b5}.xml
  FMODAssets/Metadata/AudioFile/{c9fbe6ec-426d-4880-8379-d5e69fcedc9a}.xml
  FMODAssets/Metadata/AudioFile/{d2db2930-8fed-4455-a9d8-4443edf32a9e}.xml
  FMODAssets/Metadata/AudioFile/{d67a06f7-6bfc-4016-83c8-1e7c4016eab7}.xml
  FMODAssets/Metadata/AudioFile/{dd27fb4f-f3cc-4c91-9d96-dd778bc14ebc}.xml
  FMODAssets/Metadata/AudioFile/{f05b9cfc-571e-4ed4-b78a-59beae262f9f}.xml
  FMODAssets/Metadata/AudioFile/{f067acc4-375d-4e84-a081-263640c4ffc7}.xml
  FMODAssets/Metadata/Event/{150ae508-3299-4a3b-91d3-11d1f6a946ee}.xml
  FMODAssets/Metadata/Event/{343391a5-26d7-4574-bb3c-cf496f0ac2c9}.xml
  FMODAssets/Metadata/Event/{36fbc6a5-c9a0-44fd-8c44-0013a8125d69}.xml
  FMODAssets/Metadata/Event/{4aa13862-c6cb-43b6-95be-8e3ac198c03b}.xml
  FMODAssets/Metadata/Event/{66356b52-6186-4ef2-8a8d-38474212c3fb}.xml
  FMODAssets/Metadata/Event/{6cdc22c2-5cc8-4a16-9667-856632ddc678}.xml
  FMODAssets/Metadata/Event/{9c595d95-9c82-448a-b1bc-289c019051ed}.xml
  FMODAssets/Metadata/Event/{a26757f3-458e-41e6-8e97-38fe86a61c5c}.xml
  FMODAssets/Metadata/Event/{a8a52b8e-f392-40dc-a182-137ca06f633a}.xml
  FMODAssets/Metadata/Event/{aa22e30e-f1c1-4ddc-bb6a-9165804ca5e3}.xml
  FMODAssets/Metadata/Event/{c0a42275-49b2-472d-a71e-400946aa708d}.xml
  FMODAssets/Metadata/Event/{edf3d034-e8d3-4d9a-a486-a04ed0c11e8e}.xml
  FMODAssets/Metadata/EventFolder/{052158c9-87e1-4689-b8a3-cfbebed900ba}.xml
  FMODAssets/Metadata/EventFolder/{5a46288a-b677-4b58-ba3f-48ddba6da2da}.xml
  FMODAssets/Metadata/EventFolder/{d2b6c4cb-6156-4afc-ac5c-ec1979b80dc0}.xml
  FMODAssets/Metadata/EventFolder/{e5ddd638-8ece-44dd-8929-519ddf87ecf1}.xml
  FMODAssets/Metadata/EventFolder/{eb7efdcc-8519-467f-9610-fe4234b24e86}.xml
Labels: enhancement

#121 One shotted more audios
  FMODAssets/Build/Desktop/Master.bank
  FMODAssets/Metadata/Event/{150ae508-3299-4a3b-91d3-11d1f6a946ee}.xml
  FMODAssets/Metadata/Event/{36fbc6a5-c9a0-44fd-8c44-0013a8125d69}.xml
  FMODAssets/Metadata/Event/{4aa13862-c6cb-43b6-95be-8e3ac198c03b}.xml
  FMODAssets/Metadata/Event/{66356b52-6186-4ef2-8a8d-38474212c3fb}.xml
  FMODAssets/Metadata/Event/{a8a52b8e-f392-40dc-a182-137ca06f633a}.xml
  FMODAssets/Metadata/Event/{aa22e30e-f1c1-4ddc-bb6a-9165804ca5e3}.xml
Labels: bug fix

#122 Using Animation Curves to influence strength of Bullet Spread
  Assets/_BForBoss/Tests/Mocks/MockWeaponProperties.cs
  Assets/_BForBoss/Tests/WeaponTests.cs
  Assets/_BForBoss/_Weapons/Scenes/GunRange.unity
  Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/AutoRifle.asset
  Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/SemiAutoRifle.asset
  Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/Shotgun.asset
  Assets/_BForBoss/_Weapons/Scripts/ScriptableObjects/Weapons/WeaponScriptableObject.cs
  Assets/_BForBoss/_Weapons/Scripts/Weapons/AutomaticWeaponBehaviour.cs
  Assets/_BForBoss/_Weapons/Scripts/Weapons/Weapon.cs
  Assets/_BForBoss/_Weapons/Scripts/Weapons/WeaponBehaviour.cs
Labels: enhancement

#123 Working Scene Switcher for MAC
  Assets/_BForBoss/_Utility/Scripts/Editor/SceneSwitcher/SceneSwitcherEditorWindow.cs
Labels: bug fix

#125 BFB-196: No Debug Window in Prod Build
  Assets/_BForBoss/_Core/Scripts/Debug/DebugWindow.cs
Labels: bug fix
